#!/usr/bin/env bash
# configure nginx to listen to the port 80.
sed -i 's/listen 8080 default_server;/listen 80 default_server;/' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:8080 default_server/listen [::]:80 default_server/' /etc/nginx/sites-enabled/default
service nginx restart 
